同步到原文,大量翻译示例,修typo/病句
huangjj27/async-book pull request #51
Opened 2021-02-16 10:02 UTC by RealXuChe

#50 :"原本引用的示例翻译程序已经是旧版本了，并且已经没有维护"
于是我就来更新翻译了.如果原文之后有更新,希望做个标记,我愿意翻译.

2021-02-28 23:13 UTC, huangjj27 commented
那感谢你的PR！在合并之前请确认以下几个事项：
- [ ] 是否已经从 zh-CN分支的英文代码拷贝至中文代码仓库下
- [ ] 是否在 book-zh_CN.toml 文件中更新了译者信息

2021-03-01 01:39 UTC, huangjj27 requested changes
好像有个地方有一场，请再检查一下？

2021-03-01 01:39 UTC, huangjj27 commented on src_zh-CN/01_getting_started/04_async_await_primer.md
>  ```
这里的标红是什么一回事？

2021-03-03 08:41 UTC, RealXuChe commented on src_zh-CN/01_getting_started/04_async_await_primer.md
>  ```
ｍdbook build看了一下，这里对应的内容完全正常，不知道为什么标红了.

查了一下，似乎include不是标准的markdown语法，有可能是这个原因？

2021-03-03 08:49 UTC, RealXuChe commented on src_zh-CN/01_getting_started/04_async_await_primer.md
>  ```
应该确实如此，linter没有解析include，把`{{#include ../../examples_zh-CN/01_04_async_await_primer/Cargo.toml:9:10}}`认为是普通文本，随后因为`{{#include ../../examples_zh-CN/01_04_async_await_primer/Cargo.toml:9:10}}`不符合toml语法而把这行标红。

2021-03-03 08:55 UTC, huangjj27 commented on src_zh-CN/01_getting_started/04_async_await_primer.md
>  ```
ok，那没有问题了

2021-03-03 08:56 UTC, huangjj27 approved these changes
可以合并

2021-03-03 08:57 UTC, merged